### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Callam-Boyle** [abhinaba1080/protractor-css-booster#1]
Hi,
I would really love to use this plugin, honest think it could resolve a lot of issues I'm currently having, but I can't seem to get it to work? Am I missing something? I have installed the node module, and have added the package reference to my config file, but when I try to use 'nextSiblingOf', for example, it does not recognise it and I get a javaheap crash error if I try to run it...

Cheers.

**Comment by abhinaba-ghosh** [comment]
Hi @Callam-Boyle . I would love to help you. Can you please share some code samples like [your package.json, conf.js  and the code you are trying this plugin]. I will definitely have a look into it. 

It will be great if you can share the DOM structure as well.

**Comment by Callam-Boyle** [comment]
Thanks a lot, certinly!

package.json:
`{
  "name": "protractor",
  "description": "Webdriver E2E test wrapper for Angular.",
  "author": "Person",
  "dependencies": {
    "allure-commandline": "^2.9.0",
    "allure-env-properties-adder": "^1.0.8",
    "fs": "0.0.1-security",
    "fs-extra": "^8.1.0",
    "jasmine": "2.8.0",
    "jasmine-allure-reporter": "^1.0.2",
    "jasmine-reporters": "^2.3.2",
    "jasminewd2": "^2.2.0",
    "mkdirp": "^0.5.1",
    "pg": "^7.11.0",
    "pg-promise": "^8.7.4",
    "protractor-e2e-coverage": "^1.3.0",
    "selenium-webdriver": "^3.6.0",
    "shelljs": "^0.8.3",
    "webdriver-js-extender": "2.1.0",
    "webdriver-manager": "^12.1.7"
  },
  "devDependencies": {
    "http-server": "^0.12.0",
    "jasmine-core": "^2.99.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^0.2.3",
    "karma-firefox-launcher": "^0.1.7",
    "karma-jasmine": "^0.3.8",
    "karma-junit-reporter": "^2.0.1",
    "protractor": "5.4.2",
    "protractor-css-booster": "^1.1.0"
  }
}`

conf.js:
`exports.config = {

    framework: 'jasmine',
    // chromeOnly: true,
    directConnect: true,

    specs: [
        //     // '../Tests/Smoke-Tests/BasicFunction/*-spec.js',
        //     // '../Tests/Smoke-Tests/NavigationFunctionality/*-spec.js',
        //     // '../Tests/Smoke-Tests/EventViewer/*-spec.js',
        //     // '../Tests/Smoke-Tests/Metadata/*-spec.js',
        //     // '../Tests/Smoke-Tests/DocumentActions/*-spec.js'
        //      '../Tests/Smoke-Tests/*/STRAT-958-spec.js'
    ],

    suites: {
        smoke: ['../Tests/Smoke-Tests/*/*-spec.js'],
        basic:['../Tests/Smoke-Tests/BasicFunction/*-spec.js'],
        docaction:['../Tests/Smoke-Tests/DocumentActions/*-spec.js'],
        eventview:['../Tests/Smoke-Tests/EventViewer/*-spec.js'],
        metadata:['../Tests/Smoke-Tests/Metadata/*-spec.js'],
        navandfunction:['../Tests/Smoke-Tests/NavigationFunctionality/*-spec.js'],
        restrict:['../Tests/Smoke-Tests/SecurityRestriction/*-spec.js'],
        sanity:['../Tests/Sanity-Tests/*-spec.js'],
        ie11:['../Tests/ie11-Tests/*-spec.js'],
        fileupload: ['../Tests/File-Upload/*-spec.js'],
        inprogress: ['../Tests/Smoke-Tests/*/STRAT-1108-spec.js'],
    },

    capabilities: {
        browserName: 'chrome',
        // platform: 'ANY',
        // version: 'ANY',
        chromeOptions: {
            args: ['--disable-notifications', '--disable-gpu', '--no-sandbox', "--start-maximized", "--disable-browser-side-navigation", "--disable-dev-shm-usage",  '--incognito',  "headless", 'window-size=1920,1080'],
            prefs: {
                'download': {
                    prompt_for_download: false,
                    directory_upgrade: true,
                    default_directory: '/e2e/downloads/',
                }
            }
        },
        SELENIUM_PROMISE_MANAGER: true,
        restartBrowserBetweenTests: true,
    },
    'onPrepare': function () {
        let pages = require('./pages');

        global.testServer = "stratus.stratus-alpha.wsg.local";
        global.serverUser = "jenkins";

        global.docId = "";
        global.docPage = 0;
        global.docTabCat = "";
        global.docType = "";
        global.clinicAttributeValue = "";
        global.docDate = "";
        global.newNewsDay = "";
        global.newNewsMonth = "";
        global.newNewsYear = "";
        global.userGroupName = "";
        global.restrictGroups = "";
        global.generalData = require('./data/generalData');
        global.loginData = require('./data/loginData');
        global.Pages = new pages();

        // let fs = require('fs-extra');
        let fse = require('fs-extra');
        let fs = require('fs');


        // Move history folder and Clear allure reports
        fse.emptyDir('./allure-results', function (err) {
            if (err) {console.error(err)}

            if (fs.existsSync('./allure-report/history')) {
                fse.move('./allure-report/history', './allure-results/history', { overwrite: true }, function (err) {
                    if (err) {console.error(err)}

                    fse.emptyDir('./allure-report', function (err) {
                        if (err) {console.error(err)}
                    });
                });
            }
        });

        // Added for the option of using Allure reports
        let AllureReporter = require('jasmine-allure-reporter');
        jasmine.getEnv().addReporter(new AllureReporter({
            resultsDir: 'allure-results'
        }));

        // Take screen-shot for allure-reports
        jasmine.getEnv().afterEach(function (done) {
            browser.takeScreenshot().then(function (png) {
                allure.createAttachment('Screenshot', function () {
                    return new Buffer(png, 'base64')
                }, 'image/png')();
                done();
            })
        });
    },

    'onComplete': function(){
        const AllureEnvPropsAdder = require('allure-env-properties-adder').AllureEnvPropsAdder;
        //
        jasmine.getEnv().addReporter(new AllureEnvPropsAdder({
            outputDir: './allure-results',       // optional [default: '.']
            // fileName: <file-name>,      // optional [default: 'environment.properties']
            debug: false,               // optional [default: false]
            override: true,             // optional [default: true]
            props: {                    // mandatory {K-V pairs}
                Base_URL: '',
                Environment: 'Test',
                Browser: 'Chrome',
                Browser_Version: '',
            }

        }));

        // Create Allure report
        let allure = require('allure-commandline');

        // returns ChildProcess instance
        let generation = allure(['generate', 'allure-results']);

        generation.on('exit', function(exitCode) {
            console.log('Generation is finished with code:', exitCode);
        });
    },

    jasmineNodeOpts: {
        showColors: true,
        includeStackTrace: true,
        defaultTimeoutInterval: 30000000
    },
    allScriptsTimeout: 11000000,

    plugins: [
        {
            // The module name
            package: "protractor-css-booster",
        }
    ]
};
`

example of trying to use it:


DeleteUserGroup: function (userGroupName) {
                let userGroup = element(by.cssContainingText("div.mat-list-item-content > div", userGroupName));
                let DeleteUserGroupButton = element(by.nextSiblingOf(userGroup));
                DeleteUserGroupButton.click();
            },

As I say though, I'm not sure it is a problem with the plugin as such, webstorm IDE doesn't acknowledge it as an actual keyword for example.

Thank you! :)

**Comment by abhinaba-ghosh** [comment]
@Callam-Boyle : I understood your issue. 

currently, all the inputs for css-booster plugin takes css selector not elements. so, ideally, **element(by.nextSiblingOf('your css selector for the div'));**

but, you are trying to send an element as the input. I am totally agree with you that sometimes its easy to send an element to figure out the next sibling. 

I will bring an update to this library ASAP [hopefully this week] to address this issue.

**Comment by Callam-Boyle** [comment]
Fair enough, but I'm still not convinced that is my problem. Have changed it to:

DeleteUserGroup: function (userGroupName) {
                let userGroup = element(by.css(".mat-list-item"));
                let DeleteUserGroupButton = element(by.lastChildOf(userGroup));
                DeleteUserGroupButton.click();
            },

and getting exactly the same outcome.

I'm getting 'cannot find declaration to go to' when I try to click on the plugin reference in conf file. Pretty sure its not even using the plugin and this is my problem.

**Comment by abhinaba-ghosh** [comment]
> Fair enough, but I'm still not convinced that is my problem. Have changed it to:
> 
> DeleteUserGroup: function (userGroupName) {
> let userGroup = element(by.css(".mat-list-item"));
> let DeleteUserGroupButton = element(by.lastChildOf(userGroup));
> DeleteUserGroupButton.click();
> },
> 
> and getting exactly the same outcome.
> 
> I'm getting 'cannot find declaration to go to' when I try to click on the plugin reference in conf file. Pretty sure its not even using the plugin and this is my problem.

Here also, you are sending an element inside lastChildOf. As i have already said, css-booster methods does not take element as an input. so, you should do something like:

element(by.lastChildOf('.mat-list-item'));

**Comment by abhinaba-ghosh** [comment]
In next update i will attach the type definitions properly so that you can see the declaration. Your feedback will be highly valuable in next version update. Please stay tuned!

**Comment by Callam-Boyle** [comment]
Ah, OK, gotcha, I think I have it working now, thanks a lot & sorry.

Look forward to the next version! :D

**Comment by abhinaba-ghosh** [comment]
@Callam-Boyle : css-booster 2.0 is here. Now you can use protractor prototype functions as well.

Please find the updates here: https://www.npmjs.com/package/protractor-css-booster

Let me know if this works for you.
