### ISSUE TITLE
Chain element with Protractor

### ISSUE THREAD

**Issue by xiuzhen1103** [abhinaba1080/protractor-css-booster#2]
elem returned successfully for _nextSilblingSelectedHere_ div
However, how can I get to the select tag? It doesn't work with .$('select').isDisplayed(); In Protractor works fine

<div>Test</div>
<div class="nextSilblingSelectedHere">
   <div>
     <select>
     <option>option 1</option>
    <option>option 2</option
    <option>option 3</option
     </select>
  </div>
</div>

const elem = await element(by.cssContainingText('Test')).nextSibling(); 
 const exist = await elem.$('select').isDisplayed();

**Comment by xiuzhen1103** [comment]
<div>Test</div>
<div class="nextSilblingSelectedHere">
   <div>
     <select>
     <option>option 1</option>
    <option>option 2</option
    <option>option 3</option
     </select>
  </div>
</div>

const elem = await element(by.cssContainingText('Test')).nextSibling(); 
 const exist = await elem.$('select').isDisplayed();

elem returned successfully for _nextSilblingSelectedHere_ div
However, how can I get to the select tag? It doesn't work with .$('select').isDisplayed(); In Protractor works fine

**Comment by xiuzhen1103** [comment]
![image](https://user-images.githubusercontent.com/6764095/87547737-6e41db00-c6a3-11ea-8c33-79bb5f5ec594.png)
Somehow, the question dosen't format correctly in GITHUB, please find the screenshot

**Comment by abhinaba-ghosh** [comment]
Hi @xiuzhen1103 , I am working on the same. Thanks for raising the issue.

**Comment by xiuzhen1103** [comment]
I actually find out the solution 
 elem.findElement(By.css("select")).isDisplayed()

**Comment by abhinaba-ghosh** [comment]
That's great. 
```js
await elem.element(by.css('select')).isDisplayed()
```
will also work!
